### ISSUE TITLE
[Issue] Form actions are routing to HTTP instead of HTTPS

### ISSUE THREAD

**Issue by xe1os** [counterstrikesharp-panel/css-bans-egg#1]
Not able to update or save settings in the website hosted in Pterodactyl panel.

This is happening for all the form submissions.

![image](https://github.com/user-attachments/assets/d301e2ce-e4ff-4fce-8e34-85b98707316c)

When i inspect the error in Chrome, i found the below

`<form action="http://example.com/settings/servers/update" method="POST">`

it should be https instead.

**Comment by hobsRKM** [comment]
For egg or ptero, you cant use settings panel page. Edit it directly from .env file. Https or http is purely ur ptero config, css bans doesnt have to do anything with it
